### ISSUE TITLE
action should output the new version number

### ISSUE THREAD

**Issue by y-nk** [qzb/standard-version-action#32]
The purpose is to later reuse this into a "create release action" which needs the tag name which has just been pushed.

**Comment by qzb** [comment]
It would be nice, but currently there is no straightforward way for implementing this, since standard-version doesn't expose new version number when used as a library.

**Comment by y-nk** [comment]
cant it be set as output from extracting the package.json version number after the call of standard-version?

**Comment by qzb** [comment]
No, because standard-version doesn't have to update package.json, or be used for JS apps. It would be possible to compare git tags before and after execution, but I'm not sure it's a good idea.
